name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Find open Pull Requests
        uses: ./
        id: find-pull-request
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          command: pulls.list
          state: open
          ACTIONS_STEP_DEBUG: true
      - name: Report
        run: echo "Your have ${count} open Pull Requests"
        env:
          count: ${{ steps.find-pull-request.outputs.response.length }}
