name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Find open Pull Requests
        uses: ./
        id: find-pull-request
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          command: pulls.list
          args: '{ "state": "open" }'
      - name: Debug
        run: echo "${response}"
        env:
          response: ${{ steps.find-pull-request.outputs.response}}
